### ISSUE TITLE
Not working ?

### ISSUE THREAD

**Issue by zakblacki** [ravibpatel/purchase-verifier#7]
I followed the same procedure mentioned in the doc 

![image](https://user-images.githubusercontent.com/29728429/169590440-187a9487-01f8-4c35-91bc-4d36f13e170f.png)

- Retrieved the API OAuth Client ID

![image](https://user-images.githubusercontent.com/29728429/169590559-91e6612b-a4c6-449e-aaa5-11018bb10ce0.png)

But it does not save, if I refresh it's gone also 

- And I can't verify any code 

![image](https://user-images.githubusercontent.com/29728429/169590775-3a588c54-0b6d-45ec-a9bc-40bd189d0c72.png)

I'm assuming because of this jquery not found `var $ = require("jquery");`

![image](https://user-images.githubusercontent.com/29728429/169593592-10c93e65-637e-4fd8-ba44-d7e9ccd02487.png)

**Comment by ravibpatel** [comment]
Remove "vendor" directory in the project and run "npm ci" command. Now it should work fine when running "npm start" command.

**Comment by zakblacki** [comment]
> Remove "node_modules" directory in the project and run "npm ci" command. Now it should work fine when running "npm start" command. Make sure you restore the [package-lock.json](https://github.com/ravibpatel/purchase-verifier/blob/master/package-lock.json) file to its original state before running "npm ci" command.

I did but executing `npm ci` caused this which I then executed `npm install` again 

![image](https://user-images.githubusercontent.com/29728429/169763238-8e89e369-2036-49c4-9271-257223b76b98.png)

Sadly, same problem jquery still not recognized

**Comment by ravibpatel** [comment]
Pull the project again and do the steps I told you in the last comment. It looks like your package.json and package-lock.json versions are not aligned. I tried it, and it worked for me, so it should work for you. You just have to run "npm ci" command instead of "npm install".

**Comment by zakblacki** [comment]
Thanks working, but is it possible to launch it without build app node 
(through html directly instead) which lead me back to my original problem jquery issue

**Comment by ravibpatel** [comment]
You have to migrate code to normal client side web application code, and it is possible. It should be easy. Just take out both HTML file (index.html and settings.html) and remove everything except events code from the JS file. It uses settings library to store the token. Instead, you can fetch it from your server using Ajax request.
